PapillonDesignsFinal/Models/Jewelry.cs
namespace PapillonDesignsFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Jewelry")]
    public partial class Jewelry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jewelry()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }
        [DisplayName("Jewelry Id")]
        public int JewelryId { get; set; }

        [DisplayName("Name")]
        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [DisplayName("Cost")]
        public decimal Price { get; set; }

        [Required]
        [StringLength(800)]
        public string Description { get; set; }

        [StringLength(100)]
        public string Color { get; set; }


        [DisplayName("Image")]
        [StringLength(255)]
        public string ImageURL { get; set; }

        public int JewelryTypeId { get; set; }
        [DisplayName("")]
        public virtual JewelryType JewelryType { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

PapillonDesignsFinal/Models/JewelryType.cs
namespace PapillonDesignsFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    [DisplayName("Type of Jewelry")]
    [Table("JewelryType")]
    public partial class JewelryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JewelryType()
        {
            Jewelries = new HashSet<Jewelry>();
        }

        public int JewelryTypeId { get; set; }

        [Required]
        [StringLength(100)]
        public string JewelryTypeName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jewelry> Jewelries { get; set; }
    }
}

PapillonDesignsFinal/Controllers/JewelriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PapillonDesignsFinal.Models;


namespace PapillonDesignsFinal.Controllers
{
    public class JewelriesController : Controller
    {
        private DataModel db = new DataModel();

        // GET: Jewelries
        public ActionResult Index()
        {
            var jewelries = db.Jewelries.Include(j => j.JewelryType);
            return View(jewelries.ToList());
        }

        public ActionResult Earrings()
        {
            var jewelries = db.Jewelries.Include(j => j.JewelryType);
            return View(jewelries.ToList());

        }

        public ActionResult Bracelets()
        {
            var jewelries = db.Jewelries.Include(j => j.JewelryType);
            return View(jewelries.ToList());

        }

        public ActionResult Necklaces()
        {
            var jewelries = db.Jewelries.Include(j => j.JewelryType);
            return View(jewelries.ToList());

        }

        public ActionResult Sets()
        {
            var jewelries = db.Jewelries.Include(j => j.JewelryType);
            return View(jewelries.ToList());

        }

        //GET: Earring
        //public ActionResult Earrings()
        //{
        //    Repository.EarringRepository JewelryRepo = new Repository.EarringRepository();
        //    ModelState.Clear();//model state will create a dic  object that will contain state of object. Clear because we do not need it in memory
        //    return View(Earrings());
        //}

        // GET: Jewelries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jewelry jewelry = db.Jewelries.Find(id);
            if (jewelry == null)
            {
                return HttpNotFound();
            }
            return View(jewelry);
        }

        // GET: Jewelries/Create
        public ActionResult Create()
        {
            ViewBag.JewelryTypeId = new SelectList(db.JewelryTypes, "JewelryTypeId", "JewelryTypeName");
            return View();
        }

        // POST: Jewelries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JewelryId,Title,Price,Description,Color,ImageURL,JewelryTypeId")] Jewelry jewelry)
        {
            if (ModelState.IsValid)
            {
                db.Jewelries.Add(jewelry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.JewelryTypeId = new SelectList(db.JewelryTypes, "JewelryTypeId", "JewelryTypeName", jewelry.JewelryTypeId);
            return View(jewelry);
        }

        // GET: Jewelries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jewelry jewelry = db.Jewelries.Find(id);
            if (jewelry == null)
            {
                return HttpNotFound();
            }
            ViewBag.JewelryTypeId = new SelectList(db.JewelryTypes, "JewelryTypeId", "JewelryTypeName", jewelry.JewelryTypeId);
            return View(jewelry);
        }

        // POST: Jewelries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JewelryId,Title,Price,Description,Color,ImageURL,JewelryTypeId")] Jewelry jewelry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jewelry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.JewelryTypeId = new SelectList(db.JewelryTypes, "JewelryTypeId", "JewelryTypeName", jewelry.JewelryTypeId);
            return View(jewelry);
        }

        // GET: Jewelries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jewelry jewelry = db.Jewelries.Find(id);
            if (jewelry == null)
            {
                return HttpNotFound();
            }
            return View(jewelry);
        }

        // POST: Jewelries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jewelry jewelry = db.Jewelries.Find(id);
            db.Jewelries.Remove(jewelry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PapillonDesignsFinal/Views/Jewelries/Bracelets.cshtml
@model IEnumerable<PapillonDesignsFinal.Models.Jewelry>

@{
    ViewBag.Title = "Bracelets";
}
@if (User.IsInRole("Admin"))
{
    <br />
}

<center>
    <div class="jumbotron">
        <h1>Papillon Designs</h1>
        <h2 class="homeheader">Unique jewelry for every occasion</h2>
    </div>
</center>


<p>
    <div class="row">
        <ul class="col-sm-12 mini-nav">
            <li class="col-sm-3">@Html.ActionLink("Earrings", "Earrings", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Necklaces", "Necklaces", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Sets", "Sets", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("All Jewelry", "Index", "Jewelries")</li>
        </ul>
    </div>
</p>
<center>
    <p class="jewelryheader">Bracelets List </p>
</center>


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.JewelryTypeId)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {


        if (item.JewelryTypeId == 2)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ImageURL)*@
                    <img src="~/Content/Images/@item.ImageURL" alt="jewelry image" height="150" width="155" />
                </td>

                @*<td>

                        @Html.DisplayFor(modelItem => item.JewelryTypeId)


                    </td>*@
                @if (User.IsInRole("Admin"))
                {
                    @*Trying to make it so only admin can view then put closing brackets after lines below*@
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.JewelryId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.JewelryId })
                    </td>
                }
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.JewelryId })
                </td>
                
            </tr>
        }

    }

</table>

PapillonDesignsFinal/Views/Jewelries/Create.cshtml
@model PapillonDesignsFinal.Models.Jewelry

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jewelry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JewelryTypeId, "JewelryTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JewelryTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.JewelryTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PapillonDesignsFinal/Views/Jewelries/Delete.cshtml
@model PapillonDesignsFinal.Models.Jewelry

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jewelry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JewelryType.JewelryTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JewelryType.JewelryTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PapillonDesignsFinal/Views/Jewelries/Details.cshtml
@model PapillonDesignsFinal.Models.Jewelry

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Jewelry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JewelryType.JewelryTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JewelryType.JewelryTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
            
        </dt>
        <dd>
            @*@Html.DisplayFor(model => model.ImageURL)*@
      
            <img src="~/Content/Images/@Model.ImageURL" height="250" width="255" /> 
        </dd>


    </dl>

</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.JewelryId }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

PapillonDesignsFinal/Views/Jewelries/Earrings.cshtml
@model IEnumerable<PapillonDesignsFinal.Models.Jewelry>

@{
    ViewBag.Title = "Earrings";
}
@if (User.IsInRole("Admin"))
{
    <br />
}

<center>
    <div class="jumbotron">
        <h1>Papillon Designs</h1>
        <h2 class="homeheader">Unique jewelry for every occasion</h2>
    </div>
</center>


<p>
    <div class="row">
        <ul class="col-sm-12 mini-nav">
            <li class="col-sm-3">@Html.ActionLink("Bracelets", "Bracelets", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Necklaces", "Necklaces", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Sets", "Sets", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("All Jewelry", "Index", "Jewelries")</li>
        </ul>
    </div>
</p>

<center>
    <p class="jewelryheader">Earrings List </p>
</center>


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.JewelryTypeId)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {


        if (item.JewelryTypeId == 1)
        {

            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ImageURL)*@
                    <img src="~/Content/Images/@item.ImageURL" alt="jewelry image" height="150" width="155" />
                </td>

                @*<td>

                        @Html.DisplayFor(modelItem => item.JewelryTypeId)


                    </td>*@
                @if (User.IsInRole("Admin"))
                {
                    @*Trying to make it so only admin can view then put closing brackets after lines below*@
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.JewelryId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.JewelryId })
                    </td>
                }
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.JewelryId })
                </td>
            </tr>

        }
    }

        </table>

PapillonDesignsFinal/Views/Jewelries/Index.cshtml
@model IEnumerable<PapillonDesignsFinal.Models.Jewelry>

@{
    ViewBag.Title = "Index";
}
@if (User.IsInRole("Admin"))
{
    <br />
}
<center>
    <div class="jumbotron">
        <h1>Papillon Designs</h1>
        <h2 class="homeheader">Unique jewelry for every occasion</h2>
    </div>
</center>


@if (User.IsInRole("Admin"))
{
<p>
    @Html.ActionLink("Create New", "Create")
</p>
}


<p>
    <div class="row">
        <ul class= "col-sm-12 mini-nav">
            <li class="col-sm-3">@Html.ActionLink("Earrings", "Earrings", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Bracelets", "Bracelets", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Necklaces", "Necklaces", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Sets", "Sets", "Jewelries")</li>

            @* name you want to display, name of view, name of view folder/controller  *@
        </ul>
    </div>
    </p>
<center>
    <p class="jewelryheader">All Jewelry </p>
</center>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>

        
    </tr>

@foreach (var item in Model)
{
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.ImageURL)*@
            <img src="~/Content/Images/@item.ImageURL" alt="jewelry image" height="150" width="155" />
            
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
        @if (User.IsInRole("Admin"))
        {
            @*Trying to make it so only admin can view then put closing brackets after lines below*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.JewelryId }) |    
            @Html.ActionLink("Delete", "Delete", new { id = item.JewelryId })
        </td>
        }
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.JewelryId }) 
        </td>
    </tr>

}

</table>

PapillonDesignsFinal/Views/Jewelries/Necklaces.cshtml
@model IEnumerable<PapillonDesignsFinal.Models.Jewelry>

@{
    ViewBag.Title = "Necklaces";
}
@if (User.IsInRole("Admin"))
{
    <br />
}

<center>
    <div class="jumbotron">
        <h1>Papillon Designs</h1>
        <h2 class="homeheader">Unique jewelry for every occasion</h2>
    </div>
</center>

<p>
    <div class="row">
        <ul class="col-sm-12 mini-nav">
            <li class="col-sm-3">@Html.ActionLink("Earrings", "Earrings", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Bracelets", "Bracelets", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("Sets", "Sets", "Jewelries")</li>
            <li class="col-sm-3">@Html.ActionLink("All Jewelry", "Index", "Jewelries")</li>
        </ul>
    </div>
</p>


<center>
    <p class="jewelryheader">Necklaces List </p>
</center>


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.JewelryTypeId)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {


        if (item.JewelryTypeId == 3)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ImageURL)*@
                    <img src="~/Content/Images/@item.ImageURL" alt="jewelry image" height="150" width="155" />
                </td>

                @*<td>

                        @Html.DisplayFor(modelItem => item.JewelryTypeId)


                    </td>*@
                @if (User.IsInRole("Admin"))
                {
                    @*Trying to make it so only admin can view then put closing brackets after lines below*@
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.JewelryId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.JewelryId })
                    </td>
                }
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.JewelryId })
                </td>
            </tr>

        }
    }

</table>

PapillonDesignsFinal/Views/Jewelries/Sets.cshtml
@model IEnumerable<PapillonDesignsFinal.Models.Jewelry>

@{
    ViewBag.Title = "Sets";
}
@if (User.IsInRole("Admin"))
{
    <br />
}

<center>
    <div class="jumbotron">
        <h1>Papillon Designs</h1>
        <h2 class="homeheader">Unique jewelry for every occasion</h2>
    </div>
</center>


<div class="row">
    <ul class="col-sm-12 mini-nav">
        <li class="col-sm-3">@Html.ActionLink("Earrings", "Earrings", "Jewelries")</li>
        <li class="col-sm-3">@Html.ActionLink("Bracelets", "Bracelets", "Jewelries")</li>
        <li class="col-sm-3">@Html.ActionLink("Necklaces", "Necklaces", "Jewelries")</li>
        <li class="col-sm-3">@Html.ActionLink("All Jewelry", "Index", "Jewelries")</li>
    </ul>
    </div>


    <center>
        <p class="jewelryheader">Sets List </p>
    </center>



    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageURL)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.JewelryTypeId)
                </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {


            if (item.JewelryTypeId == 4)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Color)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.ImageURL)*@
                        <img src="~/Content/Images/@item.ImageURL" alt="jewelry image" height="150" width="155" />
                    </td>

                    @*<td>

                            @Html.DisplayFor(modelItem => item.JewelryTypeId)


                        </td>*@
                    @if (User.IsInRole("Admin"))
                    {
                        @*Trying to make it so only admin can view then put closing brackets after lines below*@
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.JewelryId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.JewelryId })
                        </td>
                    }
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.JewelryId })
                    </td>
                </tr>

            }
        }

    </table>